# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Good Times Paradigms
email: tgdwyer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Examples and tutorials for various programming paradigms.
#twitter_username: immersivecola
#github_username:  tgdwyer
# Google Analytics
google_analytics: UA-159840333-1

# Build settings
markdown: kramdown
#theme: minima
remote_theme: jekyll/minima@0b7ca6b

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: "https://github.com/tgdwyer"
    - platform: x
      user_url: "https://x.com/immersivecola"

plugins_dir: _plugins

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  chapters:
    output: true
    permalink: /:name/
